// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlhmyDcd-xhpGuaARl3sPCxwy5X1GB18Y',
    appId: '1:497218353098:web:3591e3d5f45e71f6814133',
    messagingSenderId: '497218353098',
    projectId: 'authappflutter-851c9',
    authDomain: 'authappflutter-851c9.firebaseapp.com',
    storageBucket: 'authappflutter-851c9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANro90hrkHQnR0NMtC2LSI_WRgyPcBUws',
    appId: '1:497218353098:android:49731aa610e9339b814133',
    messagingSenderId: '497218353098',
    projectId: 'authappflutter-851c9',
    storageBucket: 'authappflutter-851c9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeFK6Y8-Pn0vDg7aFS-PjmDnSlQeT8IJ0',
    appId: '1:497218353098:ios:6ebbb5f591d9f13a814133',
    messagingSenderId: '497218353098',
    projectId: 'authappflutter-851c9',
    storageBucket: 'authappflutter-851c9.appspot.com',
    iosBundleId: 'com.example.authappflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeFK6Y8-Pn0vDg7aFS-PjmDnSlQeT8IJ0',
    appId: '1:497218353098:ios:6ebbb5f591d9f13a814133',
    messagingSenderId: '497218353098',
    projectId: 'authappflutter-851c9',
    storageBucket: 'authappflutter-851c9.appspot.com',
    iosBundleId: 'com.example.authappflutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlhmyDcd-xhpGuaARl3sPCxwy5X1GB18Y',
    appId: '1:497218353098:web:8282a37319944d5d814133',
    messagingSenderId: '497218353098',
    projectId: 'authappflutter-851c9',
    authDomain: 'authappflutter-851c9.firebaseapp.com',
    storageBucket: 'authappflutter-851c9.appspot.com',
  );

}